Repository hmcts/sscs-cor-frontend, pull requests merged in 2018-12, with the labels that each got.

#162 SSCS-4248 Fix S2S for test data setup
  Jenkinsfile_CNP
  README.md
  config/custom-environment-variables.json
  config/default.json
  test/fixtures/coh.ts
  test/fixtures/s2s.ts
  test/mock/s2s/services/oauth2_authoirse.js
  test/mock/s2s/services/oauth2_token.js
Labels: ns:sscs-cor-frontend-pr-162

#163 SSCS-4248 Fix S2S for test data setup
  Jenkinsfile_CNP
Labels: ns:sscs-cor-frontend-pr-163

#166 Add a way to get the S2S headers
  README.md
  create-s2s-header.ts
  package.json
  test/browser/bootstrap.ts
  test/fixtures/coh.ts
Labels: ns:sscs-cor-frontend-pr-166

#165 Evidence upload copy changes
  locale/en.json
  views/question/sending-evidence.html
Labels: ns:sscs-cor-frontend-pr-165

#168 Setup for demo these changes are taken from the demo branch.
  config/demo.json
  infrastructure/demo.tfvars
Labels: ns:sscs-cor-frontend-pr-168

#167 SSCS-4735 Clickjacking
  app/server/app.ts
  app/server/routes.ts
  package.json
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-167

#170 Fix Code coverage issues
  package.json
  test/unit/client/evidence-upload.test.ts
  test/unit/client/expanding-textbox.test.ts
  test/unit/controllers/tribunal-view.test.ts
Labels: ns:sscs-cor-frontend-pr-170

#171 [SSCS-4588] Removed multiple nested spans to fix Voiceover problem, fixed the tests…
  test/browser/1-task-list.test.ts
  test/integration/login.test.ts
  views/task-list.html
Labels: ns:sscs-cor-frontend-pr-171

#176 Voice over reads correctly questions list
  locale/en.json
  views/task-list.html
Labels: ns:sscs-cor-frontend-pr-176

#175 [SCSS-4589] cookie banner
  app/client/javascript/check-cookies.ts
  app/client/javascript/main.ts
  app/client/sass/_cookie-banner.scss
  app/client/sass/application.scss
  locale/en.json
  test/unit/client/check-cookies.test.ts
  views/includes/cookie-banner.html
  views/layout.html
Labels: ns:sscs-cor-frontend-pr-175

#177 Include files in sonar project
  sonar-project.properties
Labels: ns:sscs-cor-frontend-pr-177

#180 Set cookie path to parent directory.
  app/client/javascript/check-cookies.ts
Labels: ns:sscs-cor-frontend-pr-180

#181 Fix security vulnerabilities in node dependencies
  package-lock.json
  package.json
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-181

#182 Fix security vulnerabilities in node dependencies
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-182

#185 [SSCS-4590] Change hidden label to aria-label attribute.
  locale/en.json
  views/question/answer-form.html
Labels: ns:sscs-cor-frontend-pr-185

#186 Added back button to cookie page.
  views/policy-pages/cookie-privacy.html
Labels: ns:sscs-cor-frontend-pr-186

#187 Refactor answering a long question test
  test/page-objects/base.ts
  test/page-objects/question.ts
Labels: ns:sscs-cor-frontend-pr-187

#188 SSCS-4818 Preliminary View
  app/client/sass/_decision.scss
  app/server/app.ts
  app/server/controllers/tribunal-view.ts
  app/server/services/hearing.ts
  locale/en.json
  test/mock/cor-backend/services/hearing.js
  test/unit/controllers/decision.test.ts
  test/unit/controllers/hearing-confirm.test.ts
  test/unit/controllers/hearing-why.test.ts
  test/unit/controllers/tribunal-view-confirm.test.ts
  test/unit/controllers/tribunal-view.test.ts
  views/decision.html
  views/tribunal-view.html
Labels: ns:sscs-cor-frontend-pr-188
