Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-11, with the labels that each got.

#405 turn on MYA
  app/server/controllers/assign-case.ts
  app/server/controllers/idam-stub.ts
  app/server/controllers/login.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/utils/featureEnabled.ts
  charts/sscs-cor-frontend/values.aat.template.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  config/default.json
  package.json
  test/browser/6-mya.test.ts
  test/browser/bootstrap.ts
  test/browser/common.ts
  test/fixtures/ccd.ts
  test/integration/login.test.ts
  test/mock/cor-backend/services/citizen-assign-hearing.js
  test/mock/idam/services/login-page.js
  test/mock/idam/services/login-redirect.js
  test/mock/tribunals/data/cor/appealCreated.json
  test/mock/tribunals/services/getAppeal.js
  test/page-objects/base.ts
  test/page-objects/status.ts
  test/unit/controllers/hearing.test.ts
  test/unit/controllers/history.test.ts
  test/unit/controllers/login.test.ts
  test/unit/controllers/status.test.ts
  test/unit/controllers/task-list.test.ts
  test/unit/controllers/your-details.ts
  test/unit/middleware/ensure-authenticated.test.ts
  views/components/navigation-tabs.html
  views/includes/account-navigation.html
  views/login.html
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-405

#403 filter out evidence tab if readyToList is not Ready to list.
  app/server/middleware/ensure-authenticated.ts
  test/mock/tribunals/data/paper/appealReceived.json
  yarn-audit-issues
Labels: ns:sscs-cor-frontend-pr-403

#406 Sscs 6782
  config/default.json
Labels: ns:sscs-cor-frontend-pr-406

#407 turn on in aat
  infrastructure/aat.tfvars
Labels: ns:sscs-cor-frontend-pr-407

#408 Bug bash
  infrastructure/aat.tfvars
Labels: ns:sscs-cor-frontend-pr-408

#404 SSCS-6662 Display subscription email and sms details
  app/client/sass/application.scss
  app/server/controllers/login.ts
  app/server/controllers/your-details.ts
  charts/sscs-cor-frontend/values.preview.template.yaml
  locale/en.json
  test/unit/controllers/your-details.ts
  views/your-details.html
  yarn-audit-known-issues
Labels: ns:sscs-cor-frontend-pr-404

#414 Sscs 6662 display subscription detaills
  charts/sscs-cor-frontend/values.preview.template.yaml
  yarn-audit-known-issues
Labels: ns:sscs-cor-frontend-pr-414

#416 Sscs 6662 display subscription detaills
  infrastructure/aat.tfvars
  yarn-audit-known-issues
Labels: ns:sscs-cor-frontend-pr-416
