Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-12, with the labels that each got.

#420 Update README.md with how to run locally
  README.md
Labels: ns:sscs-cor-frontend-pr-420

#421 Sscs 6914 response date
  locale/en.json
Labels: ns:sscs-cor-frontend-pr-421

#426 Update README.md
  README.md
Labels: ns:sscs-cor-frontend-pr-426

#424 SSCS-6829 Sc number not displaying MYA
  app/server/controllers/login.ts
  test/browser/3-question.test.ts
Labels: ns:sscs-cor-frontend-pr-424

#427 add log in details using tya param
  README.md
Labels: ns:sscs-cor-frontend-pr-427

#423 Added central appinsights
  infrastructure/main.tf
Labels: ns:sscs-cor-frontend-pr-423
