Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-09, with the labels that each got.

#384 SSCS-6334 Allow non COR users to use MYA
  app/server/controllers/additional-evidence.ts
  app/server/services/additional-evidence.ts
  test/unit/controllers/additional-evidence.test.ts
Labels: ns:sscs-cor-frontend-pr-384

#393 Fix date filtering for paper cases.
  app/server/app-configurations.ts
  test/unit/app-configurations.test.ts
Labels: ns:sscs-cor-frontend-pr-393

#394 Change white listed module of infra.
  infrastructure/main.tf
Labels: ns:sscs-cor-frontend-pr-394

#395 Fix redis module for infra.
  infrastructure/main.tf
Labels: ns:sscs-cor-frontend-pr-395

#399 Sscs 6508 csrf path limited
  app/server/app.ts
  app/server/middleware/csrf.ts
  package.json
  test/page-objects/base.ts
  test/unit/client/evidence-upload.test.ts
  views/additional-evidence/evidence-options.html
  views/additional-evidence/evidence-statement.html
  views/additional-evidence/evidence-upload.html
  views/assign-case/index.html
  views/extend-deadline/confirmation-form.html
  views/hearing-confirm/index.html
  views/hearing-why/form.html
  views/includes/csrf-hidden-input.html
  views/login.html
  views/question/answer-form.html
  views/question/upload-evidence.html
  views/submit-question.html
  views/tribunal-view-confirm.html
  views/tribunal-view.html
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-399
