Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-08, with the labels that each got.

#367 SSCS-5625 Allow user to select case to view
  app/server/controllers/login.ts
  locale/en.json
  test/unit/controllers/login.test.ts
  views/select-case.html
Labels: ns:sscs-cor-frontend-pr-367

#370 Suppress hearing tab for appellants in COR
  app/server/controllers/hearing.ts
  app/server/middleware/ensure-authenticated.ts
  test/unit/middleware/ensure-authenticated.test.ts
  test/unit/routes.test.ts
  views/components/navigation-tabs.html
Labels: ns:sscs-cor-frontend-pr-370

#372 SSCS-6262 - Contact us hearing change.
  locale/en.json
Labels: ns:sscs-cor-frontend-pr-372

#363 SSCS-6103 Update location of images to hmctspublic
  acb.tpl.yaml
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/requirements.yaml
  charts/sscs-cor-frontend/values.template.yaml
Labels: ns:sscs-cor-frontend-pr-363

#371 Contactus replace with submit your appeal logic.
  app/server/app.ts
  app/server/utils/featureEnabled.ts
  config/custom-environment-variables.json
  config/default.json
  infrastructure/prod.tfvars
  locale/en.json
  package.json
  test/browser/2-extend-deadline.test.ts
  views/components/mya-contact-us.html
  views/includes/contact-us.html
  views/layout.html
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-371

#373 Prevent error if no appeal yet
  app/server/middleware/ensure-authenticated.ts
  test/browser/6-mya.test.ts
Labels: ns:sscs-cor-frontend-pr-373

#374 Fix copy path issue
  app/client/sass/_web-chat.scss
  app/client/sass/application.scss
  app/server/app-configurations.ts
  package.json
  views/layout.html
Labels: ns:sscs-cor-frontend-pr-374

#375 SSCS-6282 Add feature flag to turn on bulk scan coversheet
  app/server/controllers/additional-evidence.ts
  app/server/controllers/question.ts
  app/server/controllers/task-list.ts
  app/server/utils/featureEnabled.ts
  config/custom-environment-variables.json
  config/default.json
  test/unit/controllers/additional-evidence.test.ts
  test/unit/controllers/question.test.ts
  test/unit/controllers/task-list.test.ts
  views/additional-evidence/evidence-post.html
  views/additional-evidence/index.html
  views/includes/post-evidence.html
  views/includes/sending-evidence-contact-details.html
  views/post-evidence.html
  views/question/answer-form.html
  views/question/sending-evidence.html
Labels: ns:sscs-cor-frontend-pr-375

#376 SSCS-6294 Update layout of assign-case page
  app/server/controllers/assign-case.ts
  locale/en.json
  test/unit/controllers/assign-case.test.ts
  views/assign-case/index.html
Labels: ns:sscs-cor-frontend-pr-376

#377 Sscs 6261 add current state history
  app/server/controllers/history.ts
  locale/en.json
  test/unit/controllers/history.test.ts
  views/history.html
Labels: ns:sscs-cor-frontend-pr-377

#381 Solving bug with hearingtype
  app/server/controllers/task-list.ts
Labels: ns:sscs-cor-frontend-pr-381

#382 Enable coversheet pages
  app/server/controllers/task-list.ts
  test/unit/controllers/task-list.test.ts
Labels: ns:sscs-cor-frontend-pr-382

#379 SSCS-5907 - Update survey links.
  app/client/sass/_account-navigation.scss
  locale/en.json
  views/includes/account-navigation.html
Labels: ns:sscs-cor-frontend-pr-379

#386 SSCS-6343 - Fix ui issues
  app/client/sass/_account-navigation.scss
  app/client/sass/_contact-include.scss
  locale/en.json
Labels: ns:sscs-cor-frontend-pr-386

#387 remove deprecated config
  Jenkinsfile_CNP
Labels: ns:sscs-cor-frontend-pr-387

#389 commit change
  Jenkinsfile_nightly
Labels: ns:sscs-cor-frontend-pr-389

#390 SSCS-6314 Fix address across mya.
  locale/en.json
Labels: ns:sscs-cor-frontend-pr-390
