Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-01, with the labels that each got.

#190 Added autocomplete off
  views/login.html
  views/question/answer-form.html
Labels: ns:sscs-cor-frontend-pr-190

#192 Create docker images
  Jenkinsfile_CNP
Labels: ns:sscs-cor-frontend-pr-192

#191 Improving code coverage and test other files excluded
  .nycrc
  app/client/javascript/check-cookies.ts
  app/client/javascript/evidence-upload.ts
  app/client/javascript/expanding-textbox.ts
  app/client/javascript/main.ts
  package-lock.json
  package.json
  sonar-project.properties
  test/browser/3-question.test.ts
  test/unit/client/check-cookies.test.ts
  test/unit/client/expanding-textbox.test.ts
  test/unit/client/main.test.ts
  test/unit/controllers/submit-question.test.ts
  test/unit/routes.test.ts
Labels: ns:sscs-cor-frontend-pr-191

#193 SSCS-4484 Tribunals view content changes
  locale/en.json
  test/fixtures/coh.ts
  views/tribunal-view.html
Labels: ns:sscs-cor-frontend-pr-193

#194 Removed not necessary contact us class from decision activities.
  views/tribunal-view.html
Labels: ns:sscs-cor-frontend-pr-194

#195 Edited helmet settings to support google tag manager preview mode.
  app/server/app.ts
Labels: ns:sscs-cor-frontend-pr-195

#196 Optimise docker image build layers
  .dockerignore
  Dockerfile
Labels: ns:sscs-cor-frontend-pr-196

#197 Update question view to accommodate HTML from JUI
  app/client/sass/application.scss
  test/mock/cor-backend/services/questionData.js
  views/question/index.html
Labels: ns:sscs-cor-frontend-pr-197

#198 Split build into prod and dev.
  package.json
Labels: ns:sscs-cor-frontend-pr-198

#199 SSCS-4807 reset session timer on key press
  app/client/javascript/main.ts
  app/client/javascript/session-inactivity.ts
  app/server/controllers/session.ts
  app/server/paths.ts
  app/server/routes.ts
  package.json
  test/unit/client/main.test.ts
  test/unit/client/session-inactivity.test.ts
  test/unit/controllers/session.test.ts
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-199

#200 [SSCS-4380] Content change phase banner.
  .gitignore
  locale/en.json
  views/layout.html
Labels: ns:sscs-cor-frontend-pr-200

#201 Refactoring cookie banner and refactoring unit tests
  app/client/javascript/check-cookies.ts
  app/client/javascript/main.ts
  test/unit/client/check-cookies.test.ts
  test/unit/client/main.test.ts
Labels: ns:sscs-cor-frontend-pr-201

#203 Fixing govuk default asset path
  package.json
  views/layout.html
Labels: ns:sscs-cor-frontend-pr-203

#206 Adding modal to warn about session expiring
  .nycrc
  app/client/images/icon-important-red-inverse.png
  app/client/javascript/session-inactivity.ts
  app/client/sass/_session-modal.scss
  app/client/sass/application.scss
  app/server/controllers/session.ts
  app/server/middleware/session.ts
  locale/en.json
  test/unit/client/session-inactivity.test.ts
  views/hearing-confirm/index.html
  views/hearing-why/index.html
  views/layout.html
  views/session-inactivity-modal.html
Labels: ns:sscs-cor-frontend-pr-206

#205 [SSCS-4711] HMCTS header branding
  app/client/images/hmcts-logo.svg
  app/client/sass/application.scss
  locale/en.json
  test/page-objects/base.ts
  views/includes/header.html
  views/layout.html
Labels: ns:sscs-cor-frontend-pr-205

#209 Removed wildcard policy
  app/server/app.ts
Labels: ns:sscs-cor-frontend-pr-209

#208 Added a Compressed logo file.
  .gitignore
  app/client/images/hmcts-logo-compress.svg
  views/includes/header.html
Labels: ns:sscs-cor-frontend-pr-208

#210 Added frameAncestor directive
  app/server/app.ts
Labels: ns:sscs-cor-frontend-pr-210

#212 Enable tidam 2
  Jenkinsfile_CNP
  app/server/controllers/login.ts
  app/server/routes.ts
  app/server/services/idam.ts
  config/default.json
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  kubernetes/deployment.template.yaml
  test/browser/5-request-hearing.test.ts
  test/browser/bootstrap.ts
  test/browser/common.ts
  test/fixtures/sidam.ts
  test/page-objects/base.ts
  test/unit/controllers/login.test.ts
  test/unit/routes.test.ts
  test/unit/services/idam.test.ts
Labels: ns:sscs-cor-frontend-pr-212

#213 Getting an error message that this need to be added for builds to work
  infrastructure/main.tf
Labels: ns:sscs-cor-frontend-pr-213

#214 Load tidam secret from new vault not the old one.
  infrastructure/main.tf
Labels: ns:sscs-cor-frontend-pr-214

#216 Tidam aat
  Jenkinsfile_CNP
  app/server/controllers/login.ts
  kubernetes/deployment.template.yaml
  test/browser/common.ts
  test/page-objects/base.ts
Labels: ns:sscs-cor-frontend-pr-216

#218 Use preprod secret not test in aat
  infrastructure/main.tf
  test/fixtures/coh.ts
Labels: ns:sscs-cor-frontend-pr-218

#219 Use preprod tidam secret
  infrastructure/main.tf
  test/mocha.opts
  test/page-objects/base.ts
Labels: ns:sscs-cor-frontend-pr-219

#220 Change session timeout to 20 minutes
  config/default.json
Labels: ns:sscs-cor-frontend-pr-220
