Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-03, with the labels that each got.

#261 Add `yarn audit` to build and nightly pipelines
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:sscs-cor-frontend-pr-261

#268 SSCS-5199 Change validation message on PV confirm page.
  app/server/controllers/tribunal-view-confirm.ts
  app/server/utils/fieldValidation.ts
  locale/en.json
  test/browser/4-tribunal-view.test.ts
  test/unit/controllers/tribunal-view-confirm.test.ts
  test/unit/controllers/tribunal-view.test.ts
  test/unit/utils/field-validation.test.ts
Labels: ns:sscs-cor-frontend-pr-268

#270 SSCS-5230 Show final decision
  app/server/controllers/decision.ts
  app/server/middleware/check-decision.ts
  app/server/services/hearing.ts
  test/mock/cor-backend/services/hearing.js
  test/unit/controllers/decision.test.ts
  test/unit/controllers/hearing-confirm.test.ts
  test/unit/controllers/hearing-why.test.ts
  test/unit/controllers/tribunal-view-confirm.test.ts
  test/unit/controllers/tribunal-view.test.ts
  test/unit/middleware/check-decision.test.ts
  test/unit/routes.test.ts
Labels: ns:sscs-cor-frontend-pr-270

#271 SSCS-5218 Tables in tribunal view when empty
  views/tribunal-view.html
Labels: ns:sscs-cor-frontend-pr-271

#272 SSCS-5230 View final decision when there is no Preliminary View
  app/server/middleware/check-decision.ts
  test/unit/middleware/check-decision.test.ts
Labels: ns:sscs-cor-frontend-pr-272

#274 Align submit validation message with acceptance criteria.
  locale/en.json
Labels: ns:sscs-cor-frontend-pr-274

#273 SSCS-5221 Missing budget description in PV
  locale/en.json
Labels: ns:sscs-cor-frontend-pr-273

#275 SSCS-3973 Decision title missing
  test/integration/login.test.ts
  views/decision.html
Labels: ns:sscs-cor-frontend-pr-275

#269 Saat config
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:sscs-cor-frontend-pr-269

#278 Saat config
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:sscs-cor-frontend-pr-278

#280 SSCS-5273 Created folder and controller structure for additional info.
  app/client/javascript/evidence-upload.ts
  app/client/javascript/expanding-textbox.ts
  app/server/controllers/additional-info.ts
  app/server/paths.ts
  app/server/routes.ts
  views/additional-info/evidence-options.html
Labels: ns:sscs-cor-frontend-pr-280

#283 Saat config
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:sscs-cor-frontend-pr-283

#284 Saat config
  Jenkinsfile_parameterized
Labels: ns:sscs-cor-frontend-pr-284

#285 SSCS-5273 Added main index.html, added evidencePost page.
  app/server/controllers/additional-evidence.ts
  app/server/controllers/additional-info.ts
  app/server/paths.ts
  app/server/routes.ts
  locale/en.json
  sonar-project.properties
  views/additional-evidence/evidence-options.html
  views/additional-evidence/evidence-post.html
  views/additional-evidence/evidence-statement.html
  views/additional-evidence/evidence-upload.html
  views/additional-evidence/index.html
Labels: ns:sscs-cor-frontend-pr-285

#281 Providing additional evidence link and additional evidence landing page
  app/server/controllers/additional-evidence.ts
  locale/en.json
  test/browser/1-task-list.test.ts
  views/additional-evidence/evidence-options.html
  views/additional-evidence/evidence-post.html
  views/additional-evidence/evidence-statement.html
  views/additional-evidence/evidence-upload.html
  views/additional-evidence/index.html
  views/task-list.html
Labels: ns:sscs-cor-frontend-pr-281

#230 cnp-1131-activate acr build task
  .dockerignore
  Dockerfile
  acb.tpl.yaml
Labels: ns:sscs-cor-frontend-pr-230

#286 Adding unit and functional tests to evidence options page
  app/server/controllers/additional-evidence.ts
  test/browser/2-0-additional-evidence.test.ts
  test/page-objects/additional-evidence.ts
  test/page-objects/base.ts
  test/unit/controllers/additional-evidence.test.ts
  views/additional-evidence/evidence-options.html
  views/additional-evidence/index.html
  views/task-list.html
Labels: ns:sscs-cor-frontend-pr-286

#287 SSCS-3566
  app/server/controllers/additional-evidence.ts
  app/server/routes.ts
  app/server/services/additional-evidence.ts
  locale/en.json
  sonar-project.properties
  test/browser/2-0-additional-evidence.test.ts
  test/mock/cor-backend/services/additional-evidence-statement.js
  test/unit/controllers/additional-evidence.test.ts
  test/unit/services/additional-evidence.test.ts
  views/additional-evidence/evidence-confirm.html
  views/additional-evidence/evidence-statement.html
  views/additional-evidence/index.html
Labels: ns:sscs-cor-frontend-pr-287

#293 Currently yarn audit do not support supressing known issues with supr…
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  README.md
  bin/run-yarn-audit.sh
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/preview.tfvars
  kubernetes/deployment.template.yaml
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs-cor-frontend-pr-293

#291 Setup s2s
  app/server/controllers/additional-evidence.ts
  app/server/controllers/extend-deadline.ts
  app/server/controllers/hearing-why.ts
  app/server/controllers/login.ts
  app/server/controllers/question.ts
  app/server/controllers/submit-question.ts
  app/server/controllers/task-list.ts
  app/server/controllers/tribunal-view-confirm.ts
  app/server/routes.ts
  app/server/services/additional-evidence.ts
  app/server/services/evidence.ts
  app/server/services/hearing.ts
  app/server/services/idam.ts
  app/server/services/question.ts
  app/server/services/request-wrapper.ts
  app/server/services/s2s.ts
  config/custom-environment-variables.json
  config/default.json
  package.json
  test/fixtures/s2s.ts
  test/mock/s2s/server.js
  test/mock/s2s/services/lease.js
  test/unit/controllers/additional-evidence.test.ts
  test/unit/controllers/hearing-why.test.ts
  test/unit/controllers/login.test.ts
  test/unit/services/additional-evidence.test.ts
  test/unit/services/evidence.test.ts
  test/unit/services/hearing.test.ts
  test/unit/services/idam.test.ts
Labels: ns:sscs-cor-frontend-pr-291

#295 Excluding test coverage files from sonar
  sonar-project.properties
Labels: ns:sscs-cor-frontend-pr-295

#296 Sonar exclusions
  sonar-project.properties
Labels: ns:sscs-cor-frontend-pr-296

#297 Exclude sonar test dir
  sonar-project.properties
Labels: ns:sscs-cor-frontend-pr-297

#289 About evidence page
  app/client/sass/application.scss
  app/server/controllers/additional-evidence.ts
  app/server/paths.ts
  locale/en.json
  test/fixtures/ccd.ts
  test/fixtures/coh.ts
  test/unit/controllers/additional-evidence.test.ts
  test/unit/routes.test.ts
  views/additional-evidence/about-evidence.html
Labels: ns:sscs-cor-frontend-pr-289

#290 Refactor answer , statement text validation process.
  app/server/controllers/additional-evidence.ts
  app/server/controllers/question.ts
  app/server/utils/fieldValidation.ts
Labels: ns:sscs-cor-frontend-pr-290

#292 Added additional evidence confirm page.
  locale/en.json
  views/additional-evidence/evidence-confirm.html
  views/additional-evidence/evidence-options.html
  views/additional-evidence/evidence-post.html
  views/additional-evidence/evidence-statement.html
  views/additional-evidence/evidence-upload.html
  views/additional-evidence/index.html
Labels: ns:sscs-cor-frontend-pr-292

#300 Get sidam working in aat
  test/fixtures/sidam.ts
Labels: ns:sscs-cor-frontend-pr-300
