Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-07, with the labels that each got.

#342 SSCS-5808 Pass tya number of state to idam
  app/server/controllers/assign-case.ts
  app/server/controllers/login.ts
  app/server/paths.ts
  app/server/routes.ts
  app/server/services/hearing.ts
  package.json
  test/unit/controllers/assign-case.test.ts
  test/unit/controllers/login.test.ts
  test/unit/services/hearing.test.ts
  views/assign-case/index.html
Labels: ns:sscs-cor-frontend-pr-342

#344 SSCS-6062 Load the appeal when assigning a case to a user
  app/server/controllers/assign-case.ts
  app/server/routes.ts
  test/unit/controllers/assign-case.test.ts
Labels: ns:sscs-cor-frontend-pr-344

#349 Updated docker hmcts public registry
  Dockerfile
  acb.tpl.yaml
  package.json
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-349

#348 SSCS-6134 Load MYA even if an SC number has been set
  app/server/utils/screenReaderUtils.ts
  locale/en.json
  test/unit/utils/screenReaderUtils.ts
  views/includes/appellant-details.html
Labels: ns:sscs-cor-frontend-pr-348

#345 Mapping final stage name for paper case
  app/server/data/appealStages.ts
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs-cor-frontend-pr-345

#346 Making new MYA layout responsive
  Jenkinsfile_CNP
  app/client/sass/_account-navigation.scss
  app/client/sass/_hearing-details.scss
  app/client/sass/_navigation-tabs.scss
  app/client/sass/_task-list.scss
  app/client/sass/application.scss
  views/hearing-tab.html
  views/history.html
  views/status-tab.html
  views/task-list.html
Labels: ns:sscs-cor-frontend-pr-346

#347 - History page design chage
  app/client/sass/_history-list.scss
  app/server/app-configurations.ts
  views/history.html
Labels: ns:sscs-cor-frontend-pr-347

#351 Providence evidence tab cor and no cor cases
  app/client/sass/_task-list.scss
  locale/en.json
  test/mock/cor-backend/services/all-questions.js
  test/mock/cor-backend/services/citizen.js
  views/task-list.html
Labels: ns:sscs-cor-frontend-pr-351

#353 Your details integration
  app/client/sass/application.scss
  app/server/controllers/your-details.ts
  locale/en.json
  test/mock/cor-backend/services/citizen.js
  test/unit/controllers/your-details.ts
  views/your-details.html
Labels: ns:sscs-cor-frontend-pr-353

#355 Mapping dormant stage to Decicion and Hearing bar status
  app/server/data/appealStages.ts
Labels: ns:sscs-cor-frontend-pr-355

#357 Your details page refactoring
  views/your-details.html
Labels: ns:sscs-cor-frontend-pr-357

#358 Refactor columns width on your details page to 50%
  app/client/sass/application.scss
  views/your-details.html
Labels: ns:sscs-cor-frontend-pr-358

#359 Adding Hearing arrangements to hearing tab.
  app/server/controllers/hearing.ts
  locale/en.json
  test/mock/cor-backend/services/citizen.js
  test/unit/controllers/hearing.test.ts
  views/hearing-tab.html
Labels: ns:sscs-cor-frontend-pr-359

#360 SSCS-6098 Update get coversheet endpoint
  app/server/controllers/task-list.ts
  app/server/services/additional-evidence.ts
  test/unit/controllers/task-list.test.ts
Labels: ns:sscs-cor-frontend-pr-360

#362 Refactoring idam stubs to emulate assign journey
  app/server/controllers/idam-stub.ts
  create-test-data.ts
  test/browser/1-task-list.test.ts
  test/browser/3-question.test.ts
  test/browser/5-request-hearing.test.ts
  test/browser/bootstrap.ts
  test/browser/common.ts
  test/fixtures/ccd.ts
  test/fixtures/sidam.ts
  test/mock/cor-backend/services/get-citizen-by-tya.js
  test/mock/cor-backend/services/get-citizen.js
  test/mock/cor-backend/services/post-citizen.js
  views/login.html
Labels: ns:sscs-cor-frontend-pr-362

#364 Change survey links
  locale/en.json
  views/hearing-tab.html
  views/hearing-why/booking.html
  views/tribunal-view-accepted.html
Labels: ns:sscs-cor-frontend-pr-364

#366 Adding first functional test for MYA feature
  package.json
  test/browser/6-mya.test.ts
  test/browser/common.ts
  test/fixtures/ccd.ts
  test/mock/idam/services/login-page.js
  test/mock/idam/services/login-redirect.js
  test/mock/tribunals/data/oral/hearing.json
  test/mock/tribunals/dysonSetup.js
  test/mock/tribunals/server.js
  test/page-objects/assign-case.ts
  test/page-objects/base.ts
  test/page-objects/status.ts
Labels: ns:sscs-cor-frontend-pr-366

#368 Fix your details missing parts.
  app/server/controllers/your-details.ts
  locale/en.json
  test/unit/controllers/your-details.ts
  views/your-details.html
Labels: ns:sscs-cor-frontend-pr-368
