Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-04, with the labels that each got.

#301 Setup s2s environment variables
  infrastructure/main.tf
Labels: ns:sscs-cor-frontend-pr-301

#302 Setup s2s environment variables
  infrastructure/main.tf
Labels: ns:sscs-cor-frontend-pr-302

#299 Additional Evidence upload page
  app/client/javascript/evidence-upload.ts
  app/client/sass/application.scss
  app/server/controllers/additional-evidence.ts
  app/server/services/additional-evidence.ts
  app/server/utils/fieldValidation.ts
  locale/en.json
  sonar-project.properties
  test/mock/cor-backend/services/additional-evidence-delete.js
  test/mock/cor-backend/services/additional-evidence-get.js
  test/mock/cor-backend/services/additional-evidence-post.js
  test/mock/cor-backend/services/additional-evidence-put.js
  test/mock/cor-backend/services/additional-evidence-statement.js
  test/unit/controllers/additional-evidence.test.ts
  test/unit/services/additional-evidence.test.ts
  views/additional-evidence/about-evidence.html
  views/additional-evidence/evidence-statement.html
  views/additional-evidence/evidence-upload.html
  views/additional-evidence/index.html
  views/task-list.html
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-299

#303 When we create users give them the citizen role
  test/fixtures/sidam.ts
Labels: ns:sscs-cor-frontend-pr-303

#304 Amends on post additional evidence page
  app/client/javascript/evidence-upload.ts
  app/client/sass/application.scss
  app/server/controllers/additional-evidence.ts
  locale/en.json
  test/unit/client/evidence-upload.test.ts
  test/unit/controllers/additional-evidence.test.ts
  views/additional-evidence/evidence-post.html
  yarn-audit-known-issues
Labels: ns:sscs-cor-frontend-pr-304

#306 Amend call for saving additional statement
  app/server/services/additional-evidence.ts
Labels: ns:sscs-cor-frontend-pr-306

#307 Adding description to additional evidence file upload
  app/client/sass/application.scss
  app/server/controllers/additional-evidence.ts
  app/server/services/additional-evidence.ts
  app/server/utils/fieldValidation.ts
  locale/en.json
  test/mock/cor-backend/services/additional-evidence-statement.js
  test/unit/controllers/additional-evidence.test.ts
  test/unit/utils/field-validation.test.ts
  views/additional-evidence/evidence-upload.html
  views/additional-evidence/index.html
Labels: ns:sscs-cor-frontend-pr-307

#309 About additional evidences copy changes
  locale/en.json
  package.json
  test/browser/3-question.test.ts
  test/browser/4-tribunal-view.test.ts
  test/chai-sinon.ts
  views/additional-evidence/about-evidence.html
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-309

#308 Additional evidence upload spinner
  app/client/javascript/evidence-upload.ts
  views/additional-evidence/evidence-upload.html
  views/components/spinner.html
  views/question/answer-form.html
Labels: ns:sscs-cor-frontend-pr-308

#310 Additional evidence File Upload validations
  app/server/controllers/additional-evidence.ts
  app/server/controllers/extend-deadline.ts
  app/server/controllers/question.ts
  app/server/middleware/file-upload-validation.ts
  test/browser/3-question.test.ts
  test/browser/common.ts
  test/mocha.opts
  test/page-objects/base.ts
  test/unit/controllers/additional-evidence.test.ts
  test/unit/controllers/question.test.ts
  test/unit/middleware/file-upload-validation.test.ts
  test/unit/routes.test.ts
  views/additional-evidence/evidence-upload.html
  views/additional-evidence/index.html
  views/components/evidence-list.html
  views/errors/404.html
  views/errors/500.html
  views/question/answer-form.html
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs-cor-frontend-pr-310

#312 Refactoring Question controller to use file validation middleware
  app/server/controllers/question.ts
  test/unit/controllers/question.test.ts
  test/unit/middleware/file-upload-validation.test.ts
Labels: ns:sscs-cor-frontend-pr-312

#313 Adding files to sonar and unit tests
  app/server/controllers/tribunal-view.ts
  app/server/services/additional-evidence.ts
  sonar-project.properties
  test/unit/controllers/additional-evidence.test.ts
  test/unit/services/additional-evidence.test.ts
Labels: ns:sscs-cor-frontend-pr-313
