Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-05, with the labels that each got.

#314 Additional evidence feature flagged
  app/server/controllers/task-list.ts
  app/server/paths.ts
  app/server/routes.ts
  app/server/services/additional-evidence.ts
  app/server/utils/featureEnabled.ts
  config/default.json
  config/development.json
  locale/en.json
  test/browser/2-0-additional-evidence.test.ts
  test/mock/cor-backend/services/evidence-coversheet-get.js
  test/page-objects/additional-evidence.ts
  test/unit/controllers/task-list.test.ts
  test/unit/routes.test.ts
  test/unit/services/additional-evidence.test.ts
  test/unit/utils/featureEnabled.test.ts
  views/additional-evidence/evidence-confirm.html
  views/post-evidence.html
  views/task-list.html
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs-cor-frontend-pr-314

#317 Correcting demo config
  infrastructure/demo.tfvars
Labels: ns:sscs-cor-frontend-pr-317

#315 New Idam registration URL
  app/server/controllers/login.ts
Labels: ns:sscs-cor-frontend-pr-315

#318 fix
  Jenkinsfile_CNP
Labels: ns:sscs-cor-frontend-pr-318

#319 helm charts
  Jenkinsfile_CNP
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/requirements.yaml
  charts/sscs-cor-frontend/values.aat.template.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  charts/sscs-cor-frontend/values.template.yaml
Labels: ns:sscs-cor-frontend-pr-319

#321 Get coversheet feature
  app/server/controllers/task-list.ts
  app/server/services/additional-evidence.ts
  app/server/services/request-wrapper.ts
  test/unit/controllers/task-list.test.ts
  test/unit/services/additional-evidence.test.ts
Labels: ns:sscs-cor-frontend-pr-321

#323 Adding functional tests for additional evidence
  test/browser/2-0-additional-evidence.test.ts
  test/page-objects/additional-evidence-confirmation.ts
  test/page-objects/additional-evidence-statement.ts
  test/page-objects/additional-evidence-upload.ts
Labels: ns:sscs-cor-frontend-pr-323

#324 Adding more functional tests
  test/browser/2-0-additional-evidence.test.ts
  test/page-objects/additional-evidence-confirmation.ts
  test/page-objects/additional-evidence-post.ts
  test/page-objects/additional-evidence-upload.ts
  test/page-objects/base.ts
Labels: ns:sscs-cor-frontend-pr-324

#325 MYA main layout
  app/client/sass/_account-navigation.scss
  app/client/sass/_contact-include.scss
  app/client/sass/_navigation-tabs.scss
  app/client/sass/_task-list.scss
  app/client/sass/application.scss
  app/server/app.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/utils/featureEnabled.ts
  charts/sscs-cor-frontend/values.preview.template.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/docker.json
  config/preview.json
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  locale/en.json
  package.json
  views/components/navigation-tabs.html
  views/includes/account-navigation.html
  views/includes/contact-us.html
  views/includes/mya-contact-us.html
  views/layout.html
  views/task-list.html
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-325

#326 Feature flag tabs
  app/client/images/home.png
  views/task-list.html
Labels: ns:sscs-cor-frontend-pr-326

#327 Adding status page for MYA
  app/server/controllers/status.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/paths.ts
  app/server/routes.ts
  test/unit/middleware/ensure-authenticated.test.ts
  views/components/navigation-tabs.html
  views/status.html
  views/task-list.html
Labels: ns:sscs-cor-frontend-pr-327

#328 New component status bar
  app/client/images/tick.png
  app/client/sass/_status-bar.scss
  app/client/sass/application.scss
  charts/sscs-cor-frontend/values.preview.template.yaml
  views/components/status-bar.html
  views/status.html
Labels: ns:sscs-cor-frontend-pr-328
