Repository hmcts/sscs-cor-frontend, pull requests merged in 2019-02, with the labels that each got.

#222 Add screen reader support for HM acronym
  app/client/sass/application.scss
  locale/en.json
  views/includes/sending-evidence-contact-details.html
  views/question/sending-evidence.html
Labels: ns:sscs-cor-frontend-pr-222

#223 Added functional test reports.
  .eslintignore
  package-lock.json
  package.json
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-223

#226 Added logging and timeouts for 3rd party requests.
  app/server/services/question.ts
  config/custom-environment-variables.json
  config/default.json
  config/test.json
  test/fixtures/ccd.ts
  test/fixtures/coh.ts
  test/fixtures/s2s.ts
  test/fixtures/sidam.ts
Labels: ns:sscs-cor-frontend-pr-226

#229 Increase nav timeout , added new logging.
  config/custom-environment-variables.json
  config/default.json
  config/test.json
  test/browser/common.ts
  test/page-objects/base.ts
Labels: ns:sscs-cor-frontend-pr-229

#231 Config for prod url and tidam
  infrastructure/prod.tfvars
Labels: ns:sscs-cor-frontend-pr-231

#232 switch preprod idam url to test url.
  Jenkinsfile_CNP
  test/browser/common.ts
Labels: ns:sscs-cor-frontend-pr-232

#233 Updated functional tests to use test Idam
  Jenkinsfile_CNP
Labels: ns:sscs-cor-frontend-pr-233

#234 Revert back the IDAM urls and set a default proxy url.
  Jenkinsfile_CNP
  test/browser/common.ts
Labels: ns:sscs-cor-frontend-pr-234

#235 Add proxy to aat env correct way.
  Jenkinsfile_CNP
  test/browser/common.ts
Labels: ns:sscs-cor-frontend-pr-235

#228 Don't load test secret other than in preview.
  Jenkinsfile_CNP
  infrastructure/demo.tfvars
  kubernetes/deployment.template.yaml
  package.json
Labels: ns:sscs-cor-frontend-pr-228

#236 Revert charecter count field to regular textarea field.
  test/browser/3-question.test.ts
  views/question/answer-form.html
Labels: ns:sscs-cor-frontend-pr-236

#237 Copy changes and rules for empty activities
  locale/en.json
  views/tribunal-view.html
Labels: ns:sscs-cor-frontend-pr-237

#238 Tech. difficulties screen - try again/back link
  app/client/javascript/main.ts
  locale/en.json
  views/errors/500.html
Labels: ns:sscs-cor-frontend-pr-238

#240 upgrade azure
  infrastructure/main.tf
Labels: ns:sscs-cor-frontend-pr-240

#239 Changed evidence send address.
  locale/en.json
  test/unit/client/evidence-upload.test.ts
Labels: ns:sscs-cor-frontend-pr-239

#241 removed hostname as getting error
  infrastructure/prod.tfvars
Labels: ns:sscs-cor-frontend-pr-241

#242 Corrected register idam link looks like this is different between
  app/server/controllers/login.ts
Labels: ns:sscs-cor-frontend-pr-242

#243 Remove empty validation hearing why textarea
  app/server/utils/fieldValidation.ts
  locale/en.json
  test/browser/5-request-hearing.test.ts
  test/unit/controllers/hearing-why.test.ts
  test/unit/utils/field-validation.test.ts
  views/hearing-why/form.html
Labels: ns:sscs-cor-frontend-pr-243

#245 Change evidence upload email.
  locale/en.json
Labels: ns:sscs-cor-frontend-pr-245

#246 Rolled back url changes for prod
  infrastructure/prod.tfvars
Labels: ns:sscs-cor-frontend-pr-246

#251 Add character limit to 20000 characters
  app/server/utils/fieldValidation.ts
  locale/en.json
Labels: ns:sscs-cor-frontend-pr-251

#247 Added exit link with page header parameters.
  locale/en.json
  views/decision.html
  views/errors/404.html
  views/errors/500.html
  views/extend-deadline/index.html
  views/hearing-confirm/index.html
  views/hearing-why/index.html
  views/layout.html
  views/load-case-error.html
  views/login.html
  views/policy-pages/cookie-privacy.html
  views/question/index.html
  views/question/upload-evidence.html
  views/questions-completed.html
  views/submit-question.html
  views/task-list.html
  views/tribunal-view-accepted.html
  views/tribunal-view-confirm.html
  views/tribunal-view.html
Labels: ns:sscs-cor-frontend-pr-247

#249 change azure version to match other projects
  Jenkinsfile_CNP
  infrastructure/main.tf
Labels: ns:sscs-cor-frontend-pr-249

#250 Added exit link for accepted and rejected decision pages.
  app/server/controllers/login.ts
  locale/en.json
  test/unit/controllers/login.test.ts
  views/hearing-why/booking.html
  views/tribunal-view-accepted.html
Labels: ns:sscs-cor-frontend-pr-250

#252 Take a screenshot of the current page when tests fail
  test/browser/1-task-list.test.ts
  test/browser/2-extend-deadline.test.ts
  test/browser/3-question.test.ts
  test/browser/4-tribunal-view.test.ts
  test/browser/5-request-hearing.test.ts
Labels: ns:sscs-cor-frontend-pr-252

#244 Added default styling for text without a tag
  views/question/index.html
Labels: ns:sscs-cor-frontend-pr-244

#254 adding try/catch blocks on BasePage class
  test/page-objects/base.ts
Labels: ns:sscs-cor-frontend-pr-254

#248 Add preliminary view table columns style
  app/client/sass/application.scss
  views/tribunal-view.html
Labels: ns:sscs-cor-frontend-pr-248

#255 Refactoring App configuration and added hot reload
  app/server/app-configurations.ts
  app/server/app.ts
  app/server/watch.ts
  nodemon.json
  package-lock.json
  package.json
  views/layout.html
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-255

#259 Tidying up packages fixing security vulnabilities
  package.json
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-259

#257 SSCS-4139: Implement Crossbrowser tests in COR project
  .eslintignore
  Jenkinsfile_nightly
  config/test.json
  package.json
  test/crossbrowser/.eslintrc.json
  test/crossbrowser/helpers/BootstrapHelper.js
  test/crossbrowser/helpers/GeneralHelpers.js
  test/crossbrowser/helpers/SauceLabsReportingHelper.js
  test/crossbrowser/journeys/completeQuestions.test.js
  test/crossbrowser/pages/cor/task-list.js
  test/crossbrowser/pages/setup/authentication.js
  test/crossbrowser/pages/steps.js
  test/crossbrowser/saucelabs.conf.js
  test/crossbrowser/supportedBrowsers.js
  yarn.lock
Labels: ns:sscs-cor-frontend-pr-257

#260 Added unit tests for watch.ts
  app/server/watch.ts
  test/unit/watch.test.ts
Labels: ns:sscs-cor-frontend-pr-260

#258 Prod config endpoints
  infrastructure/prod.tfvars
Labels: ns:sscs-cor-frontend-pr-258

#263 added file for sandbox
  Jenkinsfile_parameterized
Labels: ns:sscs-cor-frontend-pr-263

#264 updated app gw
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:sscs-cor-frontend-pr-264

#265 Saat config
  Jenkinsfile_parameterized
Labels: ns:sscs-cor-frontend-pr-265

#267 SSCS-5198 Question page validation
  app/server/controllers/question.ts
  app/server/utils/fieldValidation.ts
  locale/en.json
  test/browser/3-question.test.ts
  test/unit/controllers/question.test.ts
  test/unit/utils/field-validation.test.ts
Labels: ns:sscs-cor-frontend-pr-267

#266 Sidam values for saat
  infrastructure/saat.tfvars
Labels: ns:sscs-cor-frontend-pr-266
