Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-03, with the labels that each got.

#483 Add aria-label to status-bar for screen reader
  views/components/status-bar.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-483

#484 Sscs 7220 accessibility content changes
  locale/en.json
  views/hearing-tab.html
  views/help-guides/support-hearing.html
  views/status-tab.html
  views/your-details.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-484

#490 Sscs 7175 time out
  locale/en.json
  views/status-tab.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-490

#489 Sscs 7174 links new window
  locale/en.json
  views/layout.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-489

#491 Sscs 7173 expandable content
  app/client/javascript/detailsToggle.ts
  test/unit/client/detailsToggle.test.ts
  test/unit/client/evidence-upload.test.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-491

#492 Add 'Not provided' default for empty cells
  locale/en.json
  views/your-details.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-492

#493 Pass pageTitleError flag from controller and update en.json
  app/server/controllers/additional-evidence.ts
  locale/en.json
  test/unit/controllers/additional-evidence.test.ts
  views/additional-evidence/index.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-493

#495 Ignore vulnerabilities
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs, rel:sscs-cor-frontend-pr-495

#497 Bump nodejs chart
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/requirements.yaml
Labels: ns:sscs, rel:sscs-cor-frontend-pr-497

#499 Change govukPhaseBanner from alpha to beta
  views/layout.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-499

#504 Bump chartversion
  Jenkinsfile_CNP
  charts/sscs-cor-frontend/Chart.yaml
Labels: ns:sscs, rel:sscs-cor-frontend-pr-504
