Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-01, with the labels that each got.

#432 Turn on additional evidence
  infrastructure/aat.tfvars
  yarn-audit-known-issues
Labels: ns:sscs-cor-frontend-pr-432

#428 Sscs 6982 appeal status
  app/server/controllers/status.ts
  app/server/data/appealStages.ts
  app/server/services/tyaService.ts
  locale/en.json
  test/unit/services/tyaService.test.ts
Labels: ns:sscs-cor-frontend-pr-428

#435 changed content around reps
  locale/en.json
  views/help-guides/support-representatives.html
  yarn-audit-known-issues
Labels: ns:sscs, rel:sscs-cor-frontend-pr-435

#438 SSCS-6921 Postcode REGEX on MYA is too strong
  app/server/controllers/assign-case.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-438

#436 SSCS_7098 Content for appeal received
  locale/en.json
Labels: ns:sscs, rel:sscs-cor-frontend-pr-436

#437 Sscs 7097 contextual help
  views/components/mya-contact-us.html
  views/help-guides/support-related-links.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-437

#434 sscs-7094 changed postal address
  locale/en.json
  test/unit/client/evidence-upload.test.ts
  views/includes/post-evidence.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-434

#439 SSCS-7095
  locale/en.json
  views/help-guides/support-withdraw-appeal.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-439

#440 Feature/sscs 7113 hide history tab
  app/server/controllers/history.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/utils/featureEnabled.ts
  config/default.json
  test/unit/controllers/history.test.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-440

#442 Cleaning up terraform code in prep for AKS migration
  .gitignore
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
  kubernetes/deployment.template.yaml
Labels: ns:sscs, rel:sscs-cor-frontend-pr-442

#441 SSCS-7132 add the appealNumber in the post api call
  app/server/services/additional-evidence.ts
  test/unit/services/additional-evidence.test.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-441

#443 Aks migration changes
  .dockerignore
  .nvmrc
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  acb.tpl.yaml
  app/server/app-insights.ts
  app/server/server.ts
  app/server/services/setupSecrets.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/requirements.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  charts/sscs-cor-frontend/values.yaml
  package.json
  test/unit/services/setupSecrets.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, rel:sscs-cor-frontend-pr-443

#444 fix node version on ASE
  infrastructure/main.tf
Labels: ns:sscs, rel:sscs-cor-frontend-pr-444

#445 Enabling AKS AAT Staging deployment
  Jenkinsfile_CNP
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.aat.template.yaml
  charts/sscs-cor-frontend/values.yaml
Labels: ns:sscs, rel:sscs-cor-frontend-pr-445

#446 fixing idam-pr condition
  charts/sscs-cor-frontend/requirements.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  charts/sscs-cor-frontend/values.yaml
Labels: ns:sscs, rel:sscs-cor-frontend-pr-446
