Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-11, with the labels that each got.

#585 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-585

#586 SSCS-8358 - Major Sonar bug
  app/core/tyaNunjucks.js
  app/server/controllers/idam-stub.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-586

#588 SSCS-8358 - Fix Major bug
  app/server/controllers/idam-stub.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-588

#589 SSCS-8358 - sonar scan fix
  package.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-589

#591 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-591

#592 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-592

#590 upgrade nodejs chart
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/requirements.yaml
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-590

#594 SSCS-8356:Security Hotspot error to fix in MYA
  app/server/controllers/additional-evidence.ts
  app/server/controllers/assign-case.ts
  app/server/controllers/decision.ts
  app/server/controllers/extend-deadline.ts
  app/server/controllers/hearing-confirm.ts
  app/server/controllers/hearing-why.ts
  app/server/controllers/hearing.ts
  app/server/controllers/history.ts
  app/server/controllers/login.ts
  app/server/controllers/question.ts
  app/server/controllers/questions-completed.ts
  app/server/controllers/status.ts
  app/server/controllers/submit-question.ts
  app/server/controllers/task-list.ts
  app/server/controllers/tribunal-view-accepted.ts
  app/server/controllers/tribunal-view-confirm.ts
  app/server/controllers/tribunal-view.ts
  app/server/controllers/your-details.ts
  app/server/services/additional-evidence.ts
  app/server/services/question.ts
  app/server/services/request-wrapper.ts
  package.json
  test/unit/controllers/questions-completed.test.ts
  test/unit/controllers/submit-question.test.ts
  test/unit/controllers/task-list.test.ts
  test/unit/routes.test.ts
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-594

#596 update links
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-596

#597 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-597

#599 Add minimist to resolution
  package.json
  test/crossbrowser/pages/postcode/verifyAppeallantPostCode.js
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-599

#600 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-600

#601 update audit links
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-601

#602 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-602

#598 SSCS-7956:MYA viewing notices
  app/server/controllers/outcome.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/paths.ts
  app/server/routes.ts
  app/server/services/tyaService.ts
  app/server/utils/dateUtils.ts
  app/server/utils/featureEnabled.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.aat.template.yaml
  charts/sscs-cor-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  locale/content.json
  test/mock/tribunals/data/oral/outcome.json
  test/unit/controllers/outcome.test.ts
  test/unit/middleware/ensure-authenticated.test.ts
  test/unit/services/tyaService.test.ts
  test/unit/utils/dateUtils.test.ts
  views/outcome-tab.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-598

#533 SSCS-7674: Tech debt – MYA – Migrate to the latest health library and…
  app/server/app.ts
  app/server/middleware/health.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/requirements.yaml
  config/default.json
  package.json
  sonar-project.properties
  test/unit/middleware/health.test.ts
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-533
