Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-09, with the labels that each got.

#552 updated High to Medium
  security.sh
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-552

#543 SSCS-7877 - Add metrics and logging for session non-availability
  app/server/controllers/hearing.ts
  app/server/controllers/login.ts
  app/server/controllers/status.ts
  app/server/controllers/task-list.ts
  app/server/controllers/your-details.ts
  app/server/middleware/check-decision.ts
  app/server/middleware/csrf.ts
  test/unit/controllers/hearing.test.ts
  test/unit/controllers/login.test.ts
  test/unit/controllers/status.test.ts
  test/unit/controllers/task-list.test.ts
  test/unit/controllers/your-details.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-543

#555 Ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-555

#557 sscs-8105 upgraded version for webdriverio, mocha, codeceptjs, loadsh
  Jenkinsfile_CNP
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-557

#559 updated urls in audit.json
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-559

#553 MYS E2E and Accessibility
  config/default.json
  test/browser/6-mya.cy.test.ts
  test/page-objects/base.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-553

#560 added more urls in audit.json
  audit.json
  package.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-560

#561 updated more urls
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-561

#562 updated more urls
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-562

#564 updated urls in audit.json
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-564

#563 Upgrade terraform
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-563

#565 Ignore urls
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-565

#556 SSCS-7788: MYA – Throw different error if user is navigating directly…
  Jenkinsfile_CNP
  app/server/controllers/assign-case.ts
  app/server/routes.ts
  locale/content.json
  test/unit/controllers/assign-case.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-556

#566 ignore welsh url
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-566

#569 Include tests for provide evidence functionality and accessibility checks
  test/browser/2-0-additional-evidence.test.ts
  test/browser/6-mya.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-569

#568 SSCS-7775: MYA - status and hide hearing details for Adjourn hearings
  app/server/controllers/assign-case.ts
  app/server/controllers/hearing.ts
  app/server/controllers/login.ts
  test/unit/controllers/assign-case.test.ts
  test/unit/controllers/hearing.test.ts
  test/unit/controllers/login.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-568

#567 SSCS-7464:MYA - status and hide hearing details for Not listable hear…
  app/server/controllers/assign-case.ts
  app/server/controllers/hearing.ts
  app/server/controllers/login.ts
  test/unit/controllers/assign-case.test.ts
  test/unit/controllers/hearing.test.ts
  test/unit/controllers/login.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-567
