Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-02, with the labels that each got.

#450 SCS-7143 Representatives - Adding evidence to MYA
  app/server/services/additional-evidence.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.aat.template.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  charts/sscs-cor-frontend/values.yaml
  test/browser/2-0-additional-evidence.test.ts
  test/unit/services/additional-evidence.test.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-450

#451 SSCS-7189 Integrate MYA to glue for ignoring false positives with ZAP…
  audit.json
  security.sh
Labels: ns:sscs, rel:sscs-cor-frontend-pr-451

#453 SSCS-7160-Your Details need changing to "Appeal Details"
  locale/en.json
  views/includes/account-navigation.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-453

#454 SSCS-7101 when the status is closed then display text
  locale/en.json
Labels: ns:sscs, rel:sscs-cor-frontend-pr-454

#456 SSCS-7200: Content changes to Write your statement page
  locale/en.json
  views/additional-evidence/evidence-options.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-456

#459 Update webdriverio
  package.json
  yarn.lock
Labels: ns:sscs, rel:sscs-cor-frontend-pr-459

#457 SSCS-6522 modify errortext on Status tab
  app/server/app-configurations.ts
  test/browser/1-task-list.test.ts
  test/unit/app-configurations.test.ts
  views/status-tab.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-457

#460 SSCS-7108 MYA cover sheet feature flag config
  app/server/app-configurations.ts
  app/server/services/additional-evidence.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  charts/sscs-cor-frontend/values.yaml
  config/preview.json
  test/browser/3-question.test.ts
  test/unit/services/additional-evidence.test.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-460

#461 SSCS-6911 Change error message shown to user in MYA journey if postco…
  locale/en.json
Labels: ns:sscs, rel:sscs-cor-frontend-pr-461

#463 Added security scan and updated test url
  Jenkinsfile_nightly
Labels: ns:sscs, rel:sscs-cor-frontend-pr-463

#464 Ignored app-configuration from Sonar and remove enableDocker build fr…
  Jenkinsfile_CNP
  app/server/app-insights.ts
  app/server/controllers/login.ts
  sonar-project.properties
  test/unit/controllers/login.test.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-464

#467 SSCS-7136 postcode content changes
  locale/en.json
Labels: ns:sscs, rel:sscs-cor-frontend-pr-467

#465 Added appinsight logs
  app/server/app-insights.ts
  app/server/controllers/login.ts
  test/unit/controllers/login.test.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-465

#400 Display hearing arrangrments for every type.
  app/server/controllers/hearing.ts
Labels: ns:sscs, ns:sscs-cor-frontend-pr-400, rel:sscs-cor-frontend-pr-400

#449 Added contact email and change opening times (SSCS-7179)
  locale/en.json
  test/browser/6-mya.test.ts
  views/components/mya-contact-us.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-449

#468 MYA feature flags
  app/server/app-insights.ts
  config/development.json
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:sscs, rel:sscs-cor-frontend-pr-468

#470 Reinstate aat tf file
  infrastructure/aat.tfvars
Labels: ns:sscs, rel:sscs-cor-frontend-pr-470

#471 Add defaults to variables tf
  infrastructure/aat.tfvars
  infrastructure/variables.tf
Labels: ns:sscs, rel:sscs-cor-frontend-pr-471

#474 SSCS-7253 update GA snippet code to send data to the right environment, either …
  views/includes/head.html
  views/layout.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-474

#476 fix terraform config to poin to AAT by default
  infrastructure/aat.tfvars
  infrastructure/variables.tf
Labels: ns:sscs, rel:sscs-cor-frontend-pr-476

#477 add environment global var to use it for the GA
  app/server/app-configurations.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.yaml
  views/includes/head.html
  views/layout.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-477

#473 Modified case-reference field to display case_id across pages
  app/server/controllers/assign-case.ts
  app/server/controllers/login.ts
  test/browser/3-question.test.ts
  test/mocha.opts
  test/mock/cor-backend/services/citizen-assign-hearing.js
  test/mock/cor-backend/services/citizen.js
  test/mock/cor-backend/services/get-citizen.js
  test/mock/cor-backend/services/hearing.js
  test/unit/client/evidence-upload.test.ts
  test/unit/controllers/decision.test.ts
  test/unit/controllers/hearing-confirm.test.ts
  test/unit/controllers/hearing-why.test.ts
  test/unit/controllers/login.test.ts
  test/unit/controllers/question.test.ts
  test/unit/controllers/submit-question.test.ts
  test/unit/controllers/task-list.test.ts
  test/unit/controllers/tribunal-view-confirm.test.ts
  test/unit/controllers/tribunal-view.test.ts
  test/unit/middleware/check-decision.test.ts
  test/unit/middleware/ensure-authenticated.test.ts
  test/unit/routes.test.ts
  test/unit/services/hearing.test.ts
  test/unit/services/question.test.ts
  test/unit/utils/screenReaderUtils.ts
  views/includes/appellant-details.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-473

#480 Fix uglify issue
  package.json
  yarn.lock
Labels: ns:sscs, rel:sscs-cor-frontend-pr-480

#478 Sscs 7169 error identification
  app/server/controllers/additional-evidence.ts
  locale/en.json
  test/unit/controllers/additional-evidence.test.ts
  views/additional-evidence/evidence-options.html
  views/additional-evidence/index.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-478

#482 Remove '--' before leg selector for IE11
  app/client/sass/_status-bar.scss
  views/components/status-bar.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-482

#485 Replace aside and nav tags
  views/help-guides/support-related-links.html
  yarn-audit-known-issues
Labels: ns:sscs, rel:sscs-cor-frontend-pr-485

#487 ignore vulnerabilities because they are coming from the dev deps
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs, rel:sscs-cor-frontend-pr-487

#488 SSCS-7303 MYA – Add better logging into the MYA journey
  app/server/app-insights.ts
  app/server/controllers/additional-evidence.ts
  app/server/controllers/login.ts
  test/unit/controllers/additional-evidence.test.ts
  test/unit/controllers/login.test.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-488

#481 Sscs 7167 simple issues
  app/client/sass/_status-bar.scss
  locale/en.json
  views/additional-evidence/evidence-options.html
  views/additional-evidence/evidence-statement.html
  views/components/status-bar.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-481

#486 SSCS-7170 Fix file input keyboard discovery/focus
  app/client/javascript/evidence-upload.ts
  app/client/sass/_question.scss
  app/client/sass/application.scss
  test/unit/client/evidence-upload.test.ts
  views/additional-evidence/evidence-upload.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-486
