Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-05, with the labels that each got.

#514 Update cor backend demo config
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.demo.template.yaml
  yarn-audit-known-issues
Labels: ns:sscs, rel:sscs-cor-frontend-pr-514

#516 SSCS-7420 Re-validate access token on sign out
  Jenkinsfile_CNP
  app/server/controllers/login.ts
  package.json
  test/unit/controllers/login.test.ts
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, rel:sscs-cor-frontend-pr-516

#518 SSCS-7285 MYA - Content for TYA redirect page
  app/server/routes.ts
  locale/en.json
  test/unit/routes.test.ts
  views/redirect-mya.html
Labels: ns:sscs, rel:sscs-cor-frontend-pr-518

#515 Sscs 7331=move sscs cor backend to tribunal
  app/server/services/additional-evidence.ts
  app/server/services/evidence.ts
  app/server/services/hearing.ts
  app/server/services/idam.ts
  app/server/services/question.ts
  app/server/services/setupSecrets.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.demo.template.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  charts/sscs-cor-frontend/values.yaml
  config/default.json
  package.json
  test/browser/6-mya.test.ts
  test/fixtures/ccd.ts
  test/integration/login.test.ts
  test/mock/cor-backend/services/additional-evidence-delete.js
  test/mock/cor-backend/services/additional-evidence-get.js
  test/mock/cor-backend/services/additional-evidence-post.js
  test/mock/cor-backend/services/additional-evidence-put.js
  test/mock/cor-backend/services/additional-evidence-statement.js
  test/mock/cor-backend/services/all-questions.js
  test/mock/cor-backend/services/answer.js
  test/mock/cor-backend/services/citizen-assign-hearing.js
  test/mock/cor-backend/services/citizen.js
  test/mock/cor-backend/services/deadline.js
  test/mock/cor-backend/services/evidence-coversheet-get.js
  test/mock/cor-backend/services/evidence-remove.js
  test/mock/cor-backend/services/evidence-upload.js
  test/mock/cor-backend/services/get-citizen-by-tya.js
  test/mock/cor-backend/services/get-citizen.js
  test/mock/cor-backend/services/hearing.js
  test/mock/cor-backend/services/post-citizen.js
  test/mock/cor-backend/services/question.js
  test/mock/cor-backend/services/sumbit-answer.js
  test/mock/cor-backend/services/tribunal-view.js
  test/unit/controllers/login.test.ts
  test/unit/routes.test.ts
  test/unit/services/additional-evidence.test.ts
  test/unit/services/evidence.test.ts
  test/unit/services/hearing.test.ts
  test/unit/services/idam.test.ts
  test/unit/services/question.test.ts
  test/unit/services/setupSecrets.test.ts
Labels: ns:sscs, rel:sscs-cor-frontend-pr-515

#520 Reademe update after migration of sscs-cor backend service to tribunal
  README.md
Labels: ns:sscs, rel:sscs-cor-frontend-pr-520
