Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-10, with the labels that each got.

#571 Ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-571

#572 Tests for hearing tab, coversheet navigation
  audit.json
  test/browser/2-0-additional-evidence.test.ts
  test/browser/6-mya.test.ts
  test/page-objects/additional-evidence-coversheet.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-572

#573 update audit file
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-573

#574 SSCS-8137 Fix Check Decision Exception handling
  app/server/middleware/check-decision.ts
  app/server/routes.ts
  test/unit/controllers/extend-deadline.test.ts
  test/unit/middleware/check-decision.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-574

#575 fix mya nightly
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-575

#576 update navigation for tests
  audit.json
  test/browser/2-0-additional-evidence.test.ts
  test/page-objects/additional-evidence-coversheet.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-576

#577 Add smoke tests for MYA
  package.json
  test/smoke/smoke-mya.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-577

#578 update audit links
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-578

#579 update audit links
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-579

#580 fix the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-580

#581 fix security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-581

#582 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-582

#583 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-583

#584 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-584
