Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-07, with the labels that each got.

#530 SSCS-7586 - Add Benefit Type to the title of the status page
  locale/en.json
  package.json
  views/status-tab.html
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-530

#531 fix the master build
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-531

#532 SSCS-7786 Pass TYA number correctly from static landing page
  app/server/routes.ts
  locale/en.json
  views/redirect-mya.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-532

#524 WLA-454: Hide Webchat
  .gitignore
  README.md
  app/server/app-configurations.ts
  app/server/controllers/login.ts
  config/default.json
  config/preview.json
  package.json
  sonar-project.properties
  test/mock/tribunals/data/oral/appealReceived.json
  test/mock/tribunals/data/paper/appealReceived.json
  views/components/mya-contact-us.html
  views/layout.html
  views/status-tab.html
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-524

#525 WLA-454: Global changes for Welsh
  app/client/javascript/session-inactivity.ts
  app/core/contentLookup.js
  app/server/app-configurations.ts
  app/server/app.ts
  app/server/controllers/additional-evidence.ts
  app/server/controllers/assign-case.ts
  app/server/controllers/content.js
  app/server/controllers/extend-deadline.ts
  app/server/controllers/hearing-confirm.ts
  app/server/controllers/login.ts
  app/server/controllers/notificationRedirect.js
  app/server/controllers/question.ts
  app/server/controllers/session.ts
  app/server/controllers/validateEmail.js
  app/server/data/appealStages.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/middleware/file-upload-validation.ts
  app/server/services/idam.ts
  app/server/utils/appealStages.ts
  app/server/utils/fieldValidation.ts
  locale/content.json
  locale/en.json
  package.json
  test/browser/1-task-list.test.ts
  test/browser/2-0-additional-evidence.test.ts
  test/browser/2-extend-deadline.test.ts
  test/browser/3-question.test.ts
  test/browser/4-tribunal-view.test.ts
  test/browser/5-request-hearing.test.ts
  test/browser/6-mya.test.ts
  test/integration/login.test.ts
  test/page-objects/additional-evidence-post.ts
  test/page-objects/additional-evidence-upload.ts
  test/unit/controllers/additional-evidence.test.ts
  test/unit/controllers/assign-case.test.ts
  test/unit/controllers/extend-deadline.test.ts
  test/unit/controllers/hearing-confirm.test.ts
  test/unit/controllers/hearing-why.test.ts
  test/unit/controllers/login.test.ts
  test/unit/controllers/question.test.ts
  test/unit/controllers/tribunal-view-confirm.test.ts
  test/unit/controllers/tribunal-view.test.ts
  test/unit/middleware/file-upload-validation.test.ts
  test/unit/routes.test.ts
  test/unit/utils/field-validation.test.ts
  views/redirect-mya.html
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-525

#535 Fix status bar
  views/components/status-bar.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-535

#534 SSCS-7815:MYA – File upload isn’t working
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-534

#536 sscs 7842 fixed nightly job
  Jenkinsfile_nightly
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-536

#538 updated audit.json to fix nightly build
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-538
