Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-08, with the labels that each got.

#539 SSCS-7844 Unify Contact Us form usage across site.
  views/includes/contact-us.html
  views/layout.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-539

#540 SSCS-7892 - updated audit.json
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-540

#541 added url to fix security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-541

#537 Fixed mya functional test
  Jenkinsfile_CNP
  app/server/controllers/login.ts
  app/server/services/idam.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  charts/sscs-cor-frontend/values.yaml
  config/default.json
  config/preview.json
  config/test.json
  test/browser/6-mya.test.ts
  test/browser/bootstrap.ts
  test/browser/common.ts
  test/fixtures/sidam.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-537

#545 update threadpoolsize from default 4 to 64
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.yaml
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-545

#548 brough code from fix-mya-cbt
  locale/content.json
  package.json
  sscs-cor-frontend.iml
  test/crossbrowser/journeys/completeQuestions.test.js
  test/crossbrowser/journeys/myaLandingPage.test.js
  test/crossbrowser/pages/postcode/verifyAppellantPostCode.js
  test/crossbrowser/pages/setup/authentication.js
  test/crossbrowser/pages/status/verifyStatusHeader.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-548

#549 SSCS-7890- added config for full fuctional test
  Jenkinsfile_nightly
  package.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-549

#546 Updated unwanted values
  Jenkinsfile_CNP
  config/default.json
  package.json
  test/browser/6-mya.test.ts
  test/browser/bootstrap.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-546

#550 SSCS-8042-enabled accessibility test
  package.json
  test/browser/6-mya.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-550

#551 updated pally config
  package.json
  test/browser/6-mya.test.ts
  test/browser/common.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-551
