Repository hmcts/sscs-cor-frontend, pull requests merged in 2020-12, with the labels that each got.

#604 added representative mya test
  test/browser/8-representative.mya.test.ts
  test/fixtures/ccd.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-604

#605 SSCS-8346/7 English/Welsh contact us updates
  locale/content.json
  test/browser/6-mya.cy.test.ts
  test/browser/6-mya.test.ts
  test/browser/7-mya-jp.test.ts
  test/browser/8-representative.mya.test.ts
  views/components/mya-contact-us.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-605

#606 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-606

#609 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-609
