Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-01, with the labels that each got.

#612 Upgrade dependency version
  package.json
  yarn-audit-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-612

#613 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-613

#614 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-614

#615 Add env variables in security script
  security.sh
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-615

#617 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-617

#621 Include urls in audit
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-621

#622 more false positive urls
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-622
