Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-04, with the labels that each got.

#677 Fix MYA cross browser tests
  test/crossbrowser/pages/status/verifyStatusHeader.js
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-677

#672 SSCS-8979: MYA – TypeError exceptions
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-672

#679 Reverted codeceptjs as cross-brower test are failing
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-679

#680 Ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-680

#678 sscs 9018 changed the content for uploading audio video
  locale/content.json
  views/additional-evidence/evidence-confirm.html
  views/additional-evidence/evidence-upload.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-678

#681 ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-681

#682 TA-624-Welsh And English Representative Scenarios
  package.json
  test/browser/8-representative.mya.cy.test.ts
  test/browser/common.ts
Labels: TA Team, ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-682

#684 TA-626-Welsh Appeal Details-Audio-video-tab scenarios
  test/browser/6-mya.cy.test.ts
Labels: TA Team, ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-684

#686 TA-633-Welsh-Additional Evidence Scenarios
  test/browser/2-0-additional-evidence.cy.test.ts
Labels: TA Team, ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-686

#683 sscs 8779 updated content
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-683

#687 Sscs 9018 flag for av content
  views/additional-evidence/evidence-confirm.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-687

#688 Ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-688

#671 TA-540 Adding Pa11y test for remaining pages -MYA
  test/browser/2-0-additional-evidence.cy.test.ts
  test/browser/2-0-additional-evidence.test.ts
  test/browser/6-mya.cy.test.ts
  test/browser/6-mya.test.ts
  test/browser/7-jointParty.cy.test.ts
  test/browser/7-mya-jp.test.ts
  test/browser/8-representative.mya.cy.test.ts
  test/browser/8-representative.mya.test.ts
  test/page-objects/audio-video-evidence.ts
  test/page-objects/claiming-expenses.ts
  test/page-objects/hearing.ts
  test/page-objects/representatives.ts
  test/page-objects/support-evidence.ts
  test/page-objects/support-hearing.ts
  test/page-objects/withdraw-appeal.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-671
