Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-11, with the labels that each got.

#787 Add url to env_var to run tests in multiple environments
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-787

#789 Upgrade dependency version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-789

#741 SSCS-7821: MYA – Select case – Display tab for active and non-active …
  .gitignore
  app/server/controllers/active-cases.ts
  app/server/controllers/dormant-cases.ts
  app/server/controllers/login.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/paths.ts
  app/server/routes.ts
  app/server/services/hearing.ts
  app/server/utils/featureEnabled.ts
  app/server/utils/fieldValidation.ts
  config/custom-environment-variables.json
  config/default.json
  locale/content.json
  test/browser/2-0-additional-evidence.cy.test.ts
  test/mock/tribunals/data/oral/activeAndDormantCases.json
  test/unit/controllers/active-cases.test.ts
  test/unit/controllers/dormant-cases.test.ts
  test/unit/controllers/login.test.ts
  views/active-tab.html
  views/components/navigation-main-tabs.html
  views/dormant-tab.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-741

#785 SSCS-9672: Modify health check timeout
  app/server/middleware/health.ts
  config/default.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-785

#793 SSCS-9799 - confirmation after requesting a hearing recording
  views/request-type/index.html
  views/request-type/request-confirm.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-793

#794 SSCS-9794: Welsh hearing recording request page is not found when pressing Welsh toggle from within the Requests page.
  app/client/javascript/request-type.ts
  app/server/controllers/request-type.ts
  app/server/services/request-type.ts
  test/unit/client/request-type.test.ts
  test/unit/controllers/request-type.test.ts
  views/request-type/hearing-recording.html
  views/request-type/index.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-794

#796 suppress npm warning
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-796

#797 upgrade json-schema version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-797

#795 SSCS-9822: Hearing recording request functional test
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.yaml
  test/browser/3-0-hearing-recording-request.cy.test.ts
  test/browser/3-0-hearing-recording-request.test.ts
  test/page-objects/base.ts
  test/page-objects/request-type.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-795

#792 SSCS-9593: Tech debt – Upgrade dependencies for sscs-cor-frontend
  .gitignore
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-792

#798 increse timout of select field
  test/browser/3-0-hearing-recording-request.cy.test.ts
  test/browser/3-0-hearing-recording-request.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-798

#791 SSCS-9684:New cookie page welsh content added
  app/server/app-configurations.ts
  locale/content.json
  views/layout.html
  views/policy-pages/cookie-privacy-new.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-791
