Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-05, with the labels that each got.

#691 Add dependency version on resolution
  package.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-691

#693 Fix dc failures
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-693

#689 Ignore sec scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-689

#696 SSCS-8786 - Bereavement Benefit on MYA Landing page
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-696

#697 SSCS-9185: attendanceAllowance shown on MYA Home Screen
  views/select-case.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-697

#698 Suppress warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-698

#699 add few more urls to suppress list
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-699

#700 Add Safari browser to XB MYA test suite
  test/crossbrowser/journeys/myaLandingPage.test.js
  test/crossbrowser/pages/additional-evidence/uploadEvidence.js
  test/crossbrowser/pages/postcode/verifyAppeallantPostCode.js
  test/crossbrowser/saucelabs.conf.js
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-700

#701 Upgrade browserlist package version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-701

#702 SSCS-8815: IIDB (MYA)- Update: MYA Landing page
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-702
