Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-06, with the labels that each got.

#690 SSCS-9035:Handle evidence upload error on screen
  app/server/controllers/additional-evidence.ts
  app/server/services/additional-evidence.ts
  locale/content.json
  test/unit/controllers/additional-evidence.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-690

#706 Update dependency package version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-706

#703 Sscs 8826 jsa mya page
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-703

#707 fix dependency check failure
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-707

#708 Update dependency version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-708

#711 suppress warnings related to aat
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-711

#712 Suppress security warnings related to AAT
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-712

#718 SSCS-9127 - Remove redirect urls from IDAM AAT
  Jenkinsfile_CNP
  charts/sscs-cor-frontend/values.preview.template.yaml
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-718

#717 SSCS-8954:Maternity Allowance (MYA)- Update: MYA Landing page
  app/server/controllers/login.ts
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-717

#720 Suppress idam warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-720

#709 Sscs 9157
  app/client/javascript/evidence-upload.ts
  app/server/controllers/additional-evidence.ts
  app/server/services/additional-evidence.ts
  locale/content.json
  sonar-project.properties
  test/browser/2-0-additional-evidence.cy.test.ts
  test/browser/2-0-additional-evidence.test.ts
  test/unit/client/evidence-upload.test.ts
  test/unit/controllers/additional-evidence.test.ts
  test/unit/services/additional-evidence.test.ts
  views/additional-evidence/evidence-upload.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-709

#715 Sscs 9236 2
  app/client/javascript/evidence-upload.ts
  locale/content.json
  views/additional-evidence/evidence-confirm.html
  views/additional-evidence/evidence-upload.html
  views/file-selected-modal.html
  views/includes/account-navigation.html
  views/includes/header.html
  views/layout.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-715

#722 sscs 9236 recreating PR
  app/client/javascript/evidence-upload.ts
  locale/content.json
  views/additional-evidence/evidence-confirm.html
  views/additional-evidence/evidence-upload.html
  views/file-selected-modal.html
  views/includes/account-navigation.html
  views/includes/header.html
  views/layout.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-722

#710 SSCS-9135 remove spreadsheets and powerpoints from the accepted files…
  app/server/utils/mimeTypeWhitelist.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-710

#725 Suppress warnings - ticket created to address SSCS-9180
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-725

#726 include urls to suppress
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-726
