Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-07, with the labels that each got.

#728 suppress security warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-728

#729 Suppress informational warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-729

#723 SSCS-9193: MYA – TypeError against benefitType, contact, hearingType
  app/server/controllers/additional-evidence.ts
  app/server/controllers/status.ts
  app/server/controllers/task-list.ts
  app/server/controllers/your-details.ts
  yarn-audit-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-723

#730 SSCS-9384 - Add upload AV evidence scenario to MYA
  test/browser/2-0-additional-evidence.test.ts
  test/fixtures/evidence/test_audio.mp3
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-730

#727 added cookie pref link to footer
  views/layout.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-727

#732 SSCS-9065 Social fund content
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-732

#714 added feature flag for cookie banner
  .gitignore
  app/client/javascript/check-cookies.ts
  config/custom-environment-variables.json
  config/default.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-714

#734 SSCS-8806 - Income Support MYA Landing Page
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-734

#731 SSCS-9257: Scrollable tabs
  app/client/sass/_navigation-tabs.scss
  views/components/navigation-tabs.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-731

#735 SSCS-9344: Hearing date and time checks for empty value
  views/hearing-tab.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-735

#733 SSCS-9226: MYA: New 'Requests' Tab
  app/client/javascript/main.ts
  app/client/javascript/request-type.ts
  app/client/sass/_navigation-tabs.scss
  app/server/controllers/request-type.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/paths.ts
  app/server/routes.ts
  app/server/services/request-type.ts
  app/server/utils/featureEnabled.ts
  config/custom-environment-variables.json
  config/default.json
  locale/content.json
  test/mock/tribunals/data/oral/hearing-recording.json
  test/unit/client/request-type.test.ts
  test/unit/controllers/request-type.test.ts
  test/unit/middleware/ensure-authenticated.test.ts
  test/unit/services/request-type.test.ts
  views/request-type/hearing-recording.html
  views/request-type/index.html
  views/request-type/request-confirm.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-733

#738 Suppress warnings which are addressed in a ticket
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-738

#739 more low/informational warnings suppressed
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-739

#737 SSCS-9212, SSCS-9277, SSCS-9285, SSCS-9353 - Update Mya landing page
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-737

#742 sscs 9227 welsh translation
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-742
