Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-12, with the labels that each got.

#799 suppress low security warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-799

#801 SSCS-9879: Upgrade properties-volume dependency
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-801

#802 Suppress low warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-802

#803 Suppress low warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-803

#800 SSCS-9824: Child Support - MYA: Other party Log in
  app/server/controllers/your-details.ts
  locale/content.json
  test/mock/cor-backend/services/citizen-assign-hearing.js
  test/mock/cor-backend/services/citizen.js
  test/mock/cor-backend/services/get-citizen.js
  test/mock/tribunals/data/oral/activeAndDormantCases.json
  test/unit/controllers/your-details.ts
  views/your-details.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-800
