Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-02, with the labels that each got.

#618 SSCS-8590 - Update English Contact Times
  locale/content.json
  test/browser/6-mya.test.ts
  test/browser/7-mya-jp.test.ts
  test/browser/8-representative.mya.test.ts
  views/components/mya-contact-us.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-618

#624 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-624

#625 SSCS-8595: MYA – JavaScript validation against upload for unsupported…
  app/server/controllers/additional-evidence.ts
  locale/content.json
  test/unit/controllers/additional-evidence.test.ts
  views/additional-evidence/evidence-upload.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-625

#634 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-634

#633 SSCS-8694 Upgrade Helm
  charts/sscs-cor-frontend/Chart.yaml
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-633

#635 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-635

#636 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-636

#637 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-637

#638 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-638

#639 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-639

#641 fixed sec scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-641

#642 more false positive ignores
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-642

#623 sscs 8578 labels and allow mp3 mp4
  app/server/app.ts
  app/server/controllers/additional-evidence.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/middleware/file-upload-validation.ts
  app/server/utils/featureEnabled.ts
  app/server/utils/mimeTypeWhitelist.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  locale/content.json
  test/unit/controllers/additional-evidence.test.ts
  test/unit/middleware/file-upload-validation.test.ts
  views/additional-evidence/evidence-options.html
  views/additional-evidence/evidence-upload.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-623

#643 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-643

#640 rename to MYA
  README.md
Labels: ns:sscs, prd:sscs-cor, prd:sscs-mya, rel:sscs-cor-frontend-pr-640, rel:sscs-mya-frontend-pr-640

#646 SSCS-8673 Log upload file hash
  app/server/controllers/additional-evidence.ts
  test/unit/controllers/additional-evidence.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-646

#648 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-648
