Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-03, with the labels that each got.

#650 Ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-650

#647 sscs 8661 added rtf files to the allowed types
  app/server/utils/mimeTypeWhitelist.ts
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-647

#644 sscs 8679 regex
  app/server/utils/fieldValidation.ts
  locale/content.json
  test/unit/utils/field-validation.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-644

#653 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-653

#655 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-655

#656 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-656

#654 Add cross browser tests for welsh cases in mya
  test/crossbrowser/journeys/myaLandingPage.test.js
  test/crossbrowser/pages/additional-evidence/uploadEvidence.js
  test/crossbrowser/pages/postcode/verifyAppeallantPostCode.js
  test/crossbrowser/pages/postcode/verifyAppellantPostCode.js
  test/crossbrowser/pages/status/verifyStatusHeader.js
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-654

#651 SSCS-8796 Update GTM
  views/includes/head.html
  views/layout.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-651

#660 Fix failing cross browser tests on Edge and firefox
  test/crossbrowser/journeys/myaLandingPage.test.js
  test/crossbrowser/pages/additional-evidence/uploadEvidence.js
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-660

#661 ignore false negatives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-661

#652 SSCS-8742:View Audio/Video Evidence Link - MYA
  app/server/controllers/av-evidence.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/paths.ts
  app/server/routes.ts
  app/server/services/tyaService.ts
  locale/content.json
  test/mock/tribunals/data/oral/av-evidence.json
  test/unit/controllers/av-evidence.test.ts
  test/unit/middleware/ensure-authenticated.test.ts
  test/unit/services/tyaService.test.ts
  views/av-evidence-tab.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-652

#659 sscs 8831 add google analytics to connectSrc
  app/server/app-configurations.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-659

#663 Ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-663

#664 Added cross browser tests created users should be deleted
  test/browser/teardown.ts
  test/crossbrowser/helpers/TeardownHelper.js
  test/crossbrowser/journeys/myaLandingPage.test.js
  test/crossbrowser/pages/setup/authentication.js
  test/crossbrowser/saucelabs.conf.js
  test/fixtures/sidam.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-664

#667 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-667

#666 async foreach is not deleting sidam users
  test/browser/common.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-666

#662 TA-539 Added Appeal details and AV Evidence tests
  test/browser/6-mya.test.ts
  test/page-objects/appeal-details.ts
  test/page-objects/status.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-662

#668 fixed the security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-668

#669 ignore false positives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-669

#674 removed lib from known issues files
  Jenkinsfile_CNP
  README.md
  app/server/routes.ts
  charts/sscs-cor-frontend/values.preview.template.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  test/browser/common.ts
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-674

#665 SSCS-8763: DLA (MYA)- Update: MYA Landing page
  app/server/controllers/additional-evidence.ts
  locale/content.json
  test/unit/controllers/additional-evidence.test.ts
  views/additional-evidence/evidence-confirm.html
  views/includes/account-navigation.html
  views/status-tab.html
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-665

#676 SSCS-8763: DLA(MYA) Landing page - fix nightly buil
  test/crossbrowser/pages/status/verifyStatusHeader.js
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-676
