Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-10, with the labels that each got.

#761 SSCS-9275-enable mutation tests
  Jenkinsfile_nightly
  audit.json
  package.json
  test/mutation/stryker.conf.js
  yarn-audit-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-761

#763 upgrade ansi package version
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-763

#765 SSCS-9275-fix security checks
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-765

#766 sscs 9669 added warning about deleted content
  locale/content.json
  views/additional-evidence/evidence-confirm.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-766

#767 supress low warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-767

#776 sscs undo redis upgrade
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-776

#777 Sscs 9298
  .dockerignore
  .eslintignore
  .gitignore
  .nycrc
  Jenkinsfile_CNP
  app/client/javascript/check-cookies.ts
  app/client/javascript/main.ts
  app/client/sass/_question.scss
  app/client/sass/_session-modal.scss
  app/client/sass/_task-list.scss
  app/client/sass/application.scss
  app/server/app-configurations.ts
  app/server/app.ts
  app/server/controllers/policies.ts
  app/server/paths.ts
  app/server/utils/featureEnabled.ts
  config/default.json
  gulpfile.js
  package.json
  test/browser/6-mya.cy.test.ts
  test/browser/6-mya.test.ts
  test/browser/7-jointParty.cy.test.ts
  test/browser/7-mya-jp.test.ts
  test/browser/8-representative.mya.cy.test.ts
  test/browser/8-representative.mya.test.ts
  test/crossbrowser/pages/status/verifyStatusHeader.js
  test/page-objects/additional-evidence.ts
  test/smoke/smoke-mya.test.ts
  test/unit/client/main.test.ts
  test/unit/controllers/policies.test.ts
  views/components/navigation-tabs.html
  views/hearing-tab.html
  views/layout.html
  views/login.html
  views/policy-pages/cookie-privacy-new.html
  views/policy-pages/cookie-privacy-old.html
  views/policy-pages/cookie-privacy.html
  views/policy-pages/cookie-success-banner.njk
  yarn-audit-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-777
