Repository hmcts/sscs-cor-frontend, pull requests merged in 2021-08, with the labels that each got.

#743 suppress low and informational warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-743

#744 Suppress warning and created a ticket for a fix SSCS-9476
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-744

#745 fix dependency issues
  audit.json
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-745

#740 SSCS-9447:Selected Tab display modified
  app/client/sass/_navigation-tabs.scss
  views/components/navigation-tabs.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-740

#736 SSCS-9381: Enable fortify scan
  Jenkinsfile_nightly
  package.json
  test/java/.gitignore
  test/java/build.gradle
  test/java/config/fortify-client.properties
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
  test/java/settings.gradle
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-736

#748 SSCS-9464 new nodejs
  charts/sscs-cor-frontend/Chart.yaml
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-748

#749 SSCS-9506 - Change Benefit name to Jobseeker’s Allowance (JSA)
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-749

#751 SSCS-9502: Change Benefit name from Pension Credits to Pension Credit
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-751

#752 suppress low warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-752

#753 suppress warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-753
