Repository hmcts/sscs-cor-frontend, pull requests merged in 2022-03, with the labels that each got.

#830 DTSPO-7110
  charts/sscs-cor-frontend/Chart.yaml
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-830

#833 Security script update
  audit.json
  package.json
  security.sh
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-833

#834 suppress node sass package
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-834

#835 SSCS-10236 updating helm chart versions
  charts/sscs-cor-frontend/Chart.yaml
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-835

#836 update suppression file
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-836

#839 Supress issues
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-839

#840 suppress false positives
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-840

#842 SSCS-10324-upgrade-minimist
  package.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-842

#844 Create CODEOWNERS
  CODEOWNERS
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-844
