Repository hmcts/sscs-cor-frontend, pull requests merged in 2022-06, with the labels that each got.

#874 SSCS-10632: Suppressing Dependencies
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-874

#875 update Security-Scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-875

#876 Suppress false warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-876
