Repository hmcts/sscs-cor-frontend, pull requests merged in 2022-05, with the labels that each got.

#859 Fixing Nightly Build
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-859

#862 Fixing Security Scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-862

#863 Tagging added
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-863

#865 Update script
  bin/run-yarn-audit.sh
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-865

#867 Revert "Tagging added"
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-867

#868 SSCS-10495-fix-nightly : add suppressions for security scan
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-868

#869 Disable fortify scan in nightly until secops-1839 is fixed
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-869

#870 sscs-10443-AzProviderUpdate
  infrastructure/state.tf
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-870

#871 SSCS-10443-InfraTaggingUpdate
  .gitignore
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-871

#872 Fixing Security Scan: updating audit.json
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-872

#866 Update SSCS opening hours
  infrastructure/main.tf
  locale/content.json
  test/browser/6-mya.test.ts
  test/browser/7-mya-jp.test.ts
  test/browser/8-representative.mya.test.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-866
