Repository hmcts/sscs-cor-frontend, pull requests merged in 2022-04, with the labels that each got.

#855 SSCS-10367: upgrading node, application insights and suppressing dependencies
  .nvmrc
  Dockerfile
  package.json
  yarn-audit-issues-result
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-855

#856 suppress warning
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-856

#857 SSCS-10445: Fixing DC and Security Scan
  audit.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-857
