Repository hmcts/sscs-cor-frontend, pull requests merged in 2022-01, with the labels that each got.

#805 Update “Save” button on Welsh cookie policy page
  locale/content.json
  views/policy-pages/cookie-privacy-new.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-805

#808 SSCS-9932: SSCS2-Child Support heading disappears on MYA on most tabs
  app/server/app-configurations.ts
  app/server/app.ts
  app/server/controllers/av-evidence.ts
  app/server/controllers/hearing.ts
  app/server/controllers/request-type.ts
  app/server/controllers/task-list.ts
  test/unit/app-configurations.test.ts
  test/unit/controllers/av-evidence.test.ts
  test/unit/controllers/hearing.test.ts
  test/unit/controllers/request-type.test.ts
  test/unit/controllers/task-list.test.ts
  views/av-evidence-tab.html
  views/hearing-tab.html
  views/request-type/index.html
  views/task-list.html
  yarn-audit-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-808

#807 9849 - MYA – Amend ready to list, response received and not listable status text
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-807

#809 SSCS-9829 SSCS5 - Update: MYA Landing page
  locale/content.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-809

#810 suppress warning
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-810

#812 Upgrade dependency package version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-812

#815 upgrade npm package
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-815

#816 suppress medium warnings
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-816

#817 suppress warning
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-817

#818 SSCS-9953: SSCS5 - Update: MYA - HMRC
  app/server/data/appealStages.ts
  views/components/status-bar.html
  views/status-tab.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-818

#820 Upgrade dependency package version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-820

#822 Upgrade dependency pacakge version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-822
