Repository hmcts/sscs-cor-frontend, pull requests merged in 2022-02, with the labels that each got.

#819 update av-evidence.ts
  app/server/controllers/av-evidence.ts
  views/av-evidence-tab.html
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-819

#825 fix security vulnerability issues
  audit.json
  package.json
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-825

#826 upgrade dependency version
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-826

#828 Update Chart.yaml
  charts/sscs-cor-frontend/Chart.yaml
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-828

#831 DTSP-7710: security vulnerabilities fix
  yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-831
