Repository hmcts/sscs-cor-frontend, pull requests merged in 2023-12, with the labels that each got.

#1024 SSCSCI 10
  .github/renovate.json
  .nvmrc
  Dockerfile
  README.md
  app/client/javascript/details-toggle.ts
  app/client/javascript/main.ts
  app/client/sass/_navigation-tabs.scss
  charts/sscs-cor-frontend/Chart.yaml
  docker-compose.yml
  package.json
  test/unit/client/detailsToggle.test.ts
  test/unit/client/main.test.ts
  tsconfig.json
  views/components/navigation-tabs.njk
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1024, enable_keep_helm

#1038 Revert "SSCS-22-Advanced-Security-Features-Not-Enabled"
  app/server/app.ts
  app/server/middleware/session.ts
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1038

#1040 Rename config file for redis preftest.json to perftest.json
  config/perftest.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1040
