Repository hmcts/sscs-cor-frontend, pull requests merged in 2024-06, with the labels that each got.

#1092 SSCSCI-856: Fix nightly build issues
  audit.json
  package.json
  security.sh
  test/crossbrowser/journeys/myaLandingPage.test.js
  test/crossbrowser/pages/additional-evidence/uploadEvidence.js
  test/crossbrowser/pages/status/verifyStatusHeader.js
  test/crossbrowser/saucelabs.conf.ts
  test/crossbrowser/supportedBrowsers.ts
  test/unit/services/hearing.test.ts
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1092

#1077 SSCSCI-499: upgrade node chart
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.yaml
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1077

#1087 Upgrade formidable
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1087

#1097 Bumped braces to fix CVE-2024-4068
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1097
