Repository hmcts/sscs-cor-frontend, pull requests merged in 2024-07, with the labels that each got.

#1101 Updated suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1101

#1103 Update audit urls
  audit.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1103

#1095 SSCSCI-776: remove unwanted feature flags
  README.md
  app/server/app-configurations.ts
  app/server/app.ts
  app/server/controllers/additional-evidence.ts
  app/server/controllers/policies.ts
  app/server/controllers/task-list.ts
  app/server/middleware/ensure-authenticated.ts
  app/server/middleware/fileUpload.ts
  app/server/utils/featureEnabled.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.aat.template.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  charts/sscs-cor-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/preview.json
  test/unit/controllers/additional-evidence.test.ts
  test/unit/controllers/av-evidence.test.ts
  test/unit/controllers/policies.test.ts
  test/unit/controllers/task-list.test.ts
  test/unit/middleware/ensure-authenticated.test.ts
  test/unit/middleware/fileUpload.test.ts
  views/additional-evidence/evidence-confirm.njk
  views/additional-evidence/evidence-options.njk
  views/includes/post-evidence.njk
  views/layout.njk
  views/policy-pages/cookie-privacy-old.njk
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1095
