Repository hmcts/sscs-cor-frontend, pull requests merged in 2024-03, with the labels that each got.

#1059 SSCSCI-767: Remove Jquery and Cookie Toggles
  app/server/app-configurations.ts
  app/server/app.ts
  app/server/middleware/session.ts
  app/server/utils/featureEnabled.ts
  config/custom-environment-variables.json
  config/default.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1059

#1063 Updated suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1063

#1064 Added CVE-2024-29041 to suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1064
