Repository hmcts/sscs-cor-frontend, pull requests merged in 2024-04, with the labels that each got.

#1067 Updated existing suppression id
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1067

#1065 Bumping express to 4.19.2
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1065

#1069 upgrade node to 18.17.0 to fix build
  .nvmrc
  README.md
  package.json
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1069
