Repository hmcts/sscs-cor-frontend, pull requests merged in 2024-09, with the labels that each got.

#1126 Danny fixing CSP
  app/server/app-configurations.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1126

#1127 Updated suppressions
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1127

#1128 Update Express to 4.20.0 and Sinon to 18.0.0
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1128

#1131 Suppression update
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1131
