Repository hmcts/sscs-cor-frontend, pull requests merged in 2024-08, with the labels that each got.

#1122 SSCSCI-984: Update Telephone and Webchat Opening Times
  app/common/locale/content.json
  yarn-audit-known-issues
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1122

#1117 SSCSCI-981 ws bump
  Dockerfile
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  README.md
  audit.json
  bin/run-yarn-audit.sh
  package.json
  test/browser/2-0-additional-evidence.cy.test.ts
  test/browser/2-0-additional-evidence.test.ts
  test/browser/3-0-hearing-recording-request.cy.test.ts
  test/browser/3-0-hearing-recording-request.test.ts
  test/browser/6-mya.cy.test.ts
  test/browser/6-mya.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1117

#1104 Danny -> Add dynatrace snippet
  views/layout.njk
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1104
