Repository hmcts/sscs-cor-frontend, pull requests merged in 2025-02, with the labels that each got.

#1155 SSCSCI-1548
  app/common/locale/content.json
  app/server/app.ts
  app/server/controllers/assign-case.ts
  app/server/utils/featureEnabled.ts
  charts/sscs-cor-frontend/Chart.yaml
  charts/sscs-cor-frontend/values.aat.template.yaml
  charts/sscs-cor-frontend/values.demo.template.yaml
  charts/sscs-cor-frontend/values.preview.template.yaml
  charts/sscs-cor-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  test/page-objects/assign-case.ts
  test/unit/controllers/assign-case.test.ts
  views/additional-evidence/index.njk
  views/assign-case/index.njk
  views/cases.njk
  views/help-guides/support-evidence.njk
  views/help-guides/support-hearing-expenses.njk
  views/help-guides/support-hearing.njk
  views/help-guides/support-representatives.njk
  views/help-guides/support-withdraw-appeal.njk
  views/includes/header.njk
  views/layout.njk
  views/post-evidence.njk
  views/your-details.njk
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1155

#1159 SSCSCI-1623: AzureRM bump to 4.15.0
  README.md
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:sscs-cor-frontend-pr-1159

#1167 SSCSCI-1515: MYA : MVP - Automation - English.
  test/browser/6-ibc-mya.test.ts
  test/browser/bootstrap.ts
  test/browser/common.ts
  test/fixtures/ccd.ts
  test/fixtures/iba_payload.json
  test/page-objects/base.ts
  test/page-objects/status.ts
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1167
