Repository hmcts/sscs-cor-frontend, pull requests merged in 2025-01, with the labels that each got.

#1146 Use Basic subscription for redis cache in non-prod environments
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:sscs, prd:sscs-cor, prod/no-changes, aat/destroy, rel:sscs-cor-frontend-pr-1146

#1147 test: fixed the added benefit appeal post code check
  test/crossbrowser/pages/postcode/verifyAppeallantPostCode.js
  views/components/mya-contact-us.njk
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1147

#1150 SSCSCI-1539: correct static brittle assertion
  test/browser/6-mya.cy.test.ts
Labels: ns:sscs, prd:sscs-cor

#1154 Nightly dev
  test/browser/6-mya.cy.test.ts
  test/browser/6-mya.test.ts
  test/browser/7-jointParty.cy.test.ts
  test/browser/7-mya-jp.test.ts
  test/browser/8-representative.mya.cy.test.ts
  test/browser/8-representative.mya.test.ts
  test/browser/common.ts
Labels: ns:sscs, prd:sscs-cor

#1156 Sscsci 1499 load user other cases if not in session
  app/server/controllers/cases.ts
  app/server/controllers/login.ts
  app/server/routes.ts
  app/server/utils/fieldValidation.ts
  package.json
  test/unit/controllers/cases.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1156

#1158 SSCSCI-1602: only show contactUs links relevant to appealType
  views/components/mya-contact-us.njk
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1158
