Repository hmcts/sscs-cor-frontend, pull requests merged in 2025-04, with the labels that each got.

#1181 Nightly dev - Fix XB test stage
  package.json
  yarn.lock
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1181

#1168 remove tabindex from appealReference
  views/includes/appellant-details.njk
Labels: ns:sscs, prd:sscs-cor, rel:sscs-cor-frontend-pr-1168

#1187 Updating chart library to use the OCI endpoint
  charts/sscs-cor-frontend/Chart.yaml
Labels: ns:sscs, prd:sscs-cor, enable_keep_helm, rel:sscs-cor-frontend-pr-1187
